INSERT INTO ITEM (NAME, DESCRIPTION, PRICE) VALUES 
    ('Laptop', 'A powerful laptop for work and gaming', 1200.00),
    ('Smartphone', 'The latest smartphone with advanced features', 800.00),
    ('Headphones', 'High-quality headphones for immersive audio experience', 100.00),
    ('Watch', 'Elegant wristwatch with modern design', 300.00),
    ('Camera', 'Professional camera for capturing stunning photos and videos', 1500.00),
    ('Tablet', 'Versatile tablet for productivity and entertainment', 600.00),
    ('Desktop', 'Powerful desktop computer for home and office use', 1500.00),
    ('Printer', 'High-quality printer for printing documents and photos', 200.00),
    ('Speaker', 'Premium speakers for immersive sound experience', 250.00),
    ('Monitor', 'Large monitor for enhanced productivity and gaming', 400.00),
    ('Backpack', 'Durable backpack for carrying essentials on the go', 50.00),
    ('Keyboard', 'Mechanical keyboard for precise and comfortable typing', 100.00),
    ('Mouse', 'Ergonomic mouse for smooth and precise cursor control', 50.00),
    ('Router', 'High-speed router for seamless internet connectivity', 80.00),
    ('External Hard Drive', 'Portable storage solution for backing up data', 120.00),
    ('Gaming Console', 'Latest gaming console for playing AAA titles', 400.00),
    ('Fitness Tracker', 'Smart fitness tracker for monitoring health and activity', 150.00),
    ('Smart TV', 'Internet-enabled television with streaming capabilities', 700.00),
    ('Wireless Earbuds', 'Wireless earbuds for on-the-go music and calls', 120.00),
    ('Bluetooth Speaker', 'Portable Bluetooth speaker for outdoor gatherings', 80.00),
    ('Digital Camera', 'Compact digital camera for capturing memories', 300.00),
    ('Power Bank', 'Portable power bank for charging devices on the move', 30.00),
    ('Smart Thermostat', 'Smart thermostat for energy-efficient temperature control', 150.00),
    ('Wireless Charger', 'Wireless charger for convenient device charging', 40.00),
    ('Smart Speaker', 'Voice-activated smart speaker for controlling home devices', 100.00);