INSERT INTO CUSTOMER_SOS VALUES
    (1, 'john@example.com', 'John', 'Doe'),
    (2, 'jane@example.com', 'Jane', 'Smith'),
    (3, 'mike@example.com', 'Mike', 'Johnson'),
    (4, 'anna@example.com', 'Anna', 'Taylor'),
    (5, 'alex@example.com', 'Alex', 'Brown'),
    (6, 'emily@example.com', 'Emily', 'Wilson');

INSERT INTO SALES_ORDER (ORDER_DATE, CUST_ID, ORDER_DESC, TOTAL_PRICE) VALUES ('2024-04-11 10:00:00', 1, 'Laptop, mouse, and keyboard bundle', 1350.00);
INSERT INTO SALES_ORDER (ORDER_DATE, CUST_ID, ORDER_DESC, TOTAL_PRICE) VALUES ('2024-04-11 11:30:00', 2, 'Smartphone and wireless earbuds', 920.00);
INSERT INTO SALES_ORDER (ORDER_DATE, CUST_ID, ORDER_DESC, TOTAL_PRICE) VALUES ('2024-04-11 12:45:00', 3, 'Camera', 1500.00);
INSERT INTO SALES_ORDER (ORDER_DATE, CUST_ID, ORDER_DESC, TOTAL_PRICE) VALUES ('2024-04-11 14:20:00', 4, 'Tablet and smartwatch', 900.00);
INSERT INTO SALES_ORDER (ORDER_DATE, CUST_ID, ORDER_DESC, TOTAL_PRICE) VALUES ('2024-04-11 15:50:00', 5, 'Desktop computer', 1500.00);

INSERT INTO ORDER_LINE_ITEM (ORDER_ID, ITEM_NAME, ITEM_QUANTITY) VALUES (1, 'Laptop', 1);
INSERT INTO ORDER_LINE_ITEM (ORDER_ID, ITEM_NAME, ITEM_QUANTITY) VALUES (1, 'Mouse', 1);
INSERT INTO ORDER_LINE_ITEM (ORDER_ID, ITEM_NAME, ITEM_QUANTITY) VALUES (1, 'Keyboard', 1);
INSERT INTO ORDER_LINE_ITEM (ORDER_ID, ITEM_NAME, ITEM_QUANTITY) VALUES (2, 'Smartphone', 1);
INSERT INTO ORDER_LINE_ITEM (ORDER_ID, ITEM_NAME, ITEM_QUANTITY) VALUES (2, 'Wireless Earbuds', 1);
INSERT INTO ORDER_LINE_ITEM (ORDER_ID, ITEM_NAME, ITEM_QUANTITY) VALUES (3, 'Camera', 1);
INSERT INTO ORDER_LINE_ITEM (ORDER_ID, ITEM_NAME, ITEM_QUANTITY) VALUES (4, 'Tablet', 1);
INSERT INTO ORDER_LINE_ITEM (ORDER_ID, ITEM_NAME, ITEM_QUANTITY) VALUES (4, 'Watch', 1);
INSERT INTO ORDER_LINE_ITEM (ORDER_ID, ITEM_NAME, ITEM_QUANTITY) VALUES (5, 'Desktop', 1);
